from re import sub


def format_name(card: str) -> str:
    return sub(r"[^a-z\-]", "", card.lower().replace(" ", "-"))


TOWERS = [
    "ally-king-tower",
    "ally-princess-tower",
    "enemy-king-tower",
    "enemy-princess-tower",
]

CARDS = [
    "archer-queen",
    "archers",
    "arrows",
    "baby-dragon",
    "balloon",
    "bandit",
    "barbarian-barrel",
    "barbarian-hut",
    "barbarians",
    "bats",
    "battle-healer",
    "battle-ram",
    "berserker",
    "bomb-tower",
    "bomber",
    "boss-bandit",
    "bowler",
    "cannon",
    "cannon-cart",
    "clone",
    "cursed-hog",
    "dark-prince",
    "dart-goblin",
    "earthquake",
    "electro-dragon",
    "electro-giant",
    "electro-spirit",
    "electro-wizard",
    "elite-barbarians",
    "elixir-collector",
    "elixir-golem",
    "enemy-archer-queen",
    "enemy-archers",
    "enemy-arrows",
    "enemy-baby-dragon",
    "enemy-balloon",
    "enemy-bandit",
    "enemy-barbarian-barrel",
    "enemy-barbarian-hut",
    "enemy-barbarians",
    "enemy-bats",
    "enemy-battle-healer",
    "enemy-battle-ram",
    "enemy-berserker",
    "enemy-bomb-tower",
    "enemy-bomber",
    "enemy-boss-bandit",
    "enemy-bowler",
    "enemy-cannon",
    "enemy-cannon-cart",
    "enemy-clone",
    "enemy-cursed-hog",
    "enemy-dark-prince",
    "enemy-dart-goblin",
    "enemy-earthquake",
    "enemy-electro-dragon",
    "enemy-electro-giant",
    "enemy-electro-spirit",
    "enemy-electro-wizard",
    "enemy-elite-barbarians",
    "enemy-elixir-collector",
    "enemy-elixir-golem",
    "enemy-executioner",
    "enemy-fire-spirit",
    "enemy-fireball",
    "enemy-firecracker",
    "enemy-fisherman",
    "enemy-flying-machine",
    "enemy-freeze",
    "enemy-furnace",
    "enemy-giant",
    "enemy-giant-skeleton",
    "enemy-giant-snowball",
    "enemy-goblin-barrel",
    "enemy-goblin-brawler",
    "enemy-goblin-cage",
    "enemy-goblin-curse",
    "enemy-goblin-demolisher",
    "enemy-goblin-drill",
    "enemy-goblin-gang",
    "enemy-goblin-giant",
    "enemy-goblin-hut",
    "enemy-goblin-machine",
    "enemy-goblins",
    "enemy-goblinstein",
    "enemy-golden-knight",
    "enemy-golem",
    "enemy-graveyard",
    "enemy-guards",
    "enemy-heal-spirit",
    "enemy-hog-rider",
    "enemy-hunter",
    "enemy-ice-golem",
    "enemy-ice-spirit",
    "enemy-ice-wizard",
    "enemy-inferno-dragon",
    "enemy-inferno-tower",
    "enemy-knight",
    "enemy-lava-hound",
    "enemy-lightning",
    "enemy-little-prince",
    "enemy-lumberjack",
    "enemy-magic-archer",
    "enemy-mega-knight",
    "enemy-mega-minion",
    "enemy-mighty-miner",
    "enemy-miner",
    "enemy-mini-pekka",
    "enemy-minion-horde",
    "enemy-minions",
    "enemy-mirror",
    "enemy-monk",
    "enemy-mortar",
    "enemy-mother-witch",
    "enemy-musketeer",
    "enemy-night-witch",
    "enemy-pekka",
    "enemy-phoenix",
    "enemy-poison",
    "enemy-prince",
    "enemy-princess",
    "enemy-rage",
    "enemy-ram-rider",
    "enemy-rascals",
    "enemy-rocket",
    "enemy-royal-delivery",
    "enemy-royal-ghost",
    "enemy-royal-giant",
    "enemy-royal-hogs",
    "enemy-royal-recruits",
    "enemy-rune-giant",
    "enemy-skeleton-army",
    "enemy-skeleton-barrel",
    "enemy-skeleton-dragons",
    "enemy-skeleton-king",
    "enemy-skeletons",
    "enemy-sparky",
    "enemy-spear-goblins",
    "enemy-spirit-empress",
    "enemy-suspicious-bush",
    "enemy-tesla",
    "enemy-the-log",
    "enemy-three-musketeers",
    "enemy-tombstone",
    "enemy-tornado",
    "enemy-valkyrie",
    "enemy-vines",
    "enemy-void",
    "enemy-wall-breakers",
    "enemy-witch",
    "enemy-wizard",
    "enemy-x-bow",
    "enemy-zap",
    "enemy-zappies",
    "executioner",
    "fire-spirit",
    "fireball",
    "firecracker",
    "fisherman",
    "flying-machine",
    "freeze",
    "furnace",
    "giant",
    "giant-skeleton",
    "giant-snowball",
    "goblin-barrel",
    "goblin-brawler",
    "goblin-cage",
    "goblin-curse",
    "goblin-demolisher",
    "goblin-drill",
    "goblin-gang",
    "goblin-giant",
    "goblin-hut",
    "goblin-machine",
    "goblins",
    "goblinstein",
    "golden-knight",
    "golem",
    "graveyard",
    "guards",
    "heal-spirit",
    "hog-rider",
    "hunter",
    "ice-golem",
    "ice-spirit",
    "ice-wizard",
    "inferno-dragon",
    "inferno-tower",
    "knight",
    "lava-hound",
    "lightning",
    "little-prince",
    "lumberjack",
    "magic-archer",
    "mega-knight",
    "mega-minion",
    "mighty-miner",
    "miner",
    "mini-pekka",
    "minion-horde",
    "minions",
    "mirror",
    "monk",
    "mortar",
    "mother-witch",
    "musketeer",
    "night-witch",
    "pekka",
    "phoenix",
    "poison",
    "prince",
    "princess",
    "rage",
    "ram-rider",
    "rascals",
    "rocket",
    "royal-delivery",
    "royal-ghost",
    "royal-giant",
    "royal-hogs",
    "royal-recruits",
    "rune-giant",
    "skeleton-army",
    "skeleton-barrel",
    "skeleton-dragons",
    "skeleton-king",
    "skeletons",
    "sparky",
    "spear-goblins",
    "spirit-empress",
    "suspicious-bush",
    "tesla",
    "the-log",
    "three-musketeers",
    "tombstone",
    "tornado",
    "valkyrie",
    "vines",
    "void",
    "wall-breakers",
    "witch",
    "wizard",
    "x-bow",
    "zap",
    "zappies",
]


ELIXIR_COST = {
    "Knight": 3,
    "Archers": 3,
    "Goblins": 2,
    "Giant": 5,
    "P.E.K.K.A": 7,
    "Minions": 3,
    "Balloon": 5,
    "Witch": 5,
    "Barbarians": 5,
    "Golem": 8,
    "Skeletons": 1,
    "Valkyrie": 4,
    "Skeleton Army": 3,
    "Bomber": 2,
    "Musketeer": 4,
    "Baby Dragon": 4,
    "Prince": 5,
    "Wizard": 5,
    "Mini P.E.K.K.A": 4,
    "Spear Goblins": 2,
    "Giant Skeleton": 6,
    "Hog Rider": 4,
    "Minion Horde": 5,
    "Ice Wizard": 3,
    "Royal Giant": 6,
    "Guards": 3,
    "Princess": 3,
    "Dark Prince": 4,
    "Three Musketeers": 9,
    "Lava Hound": 7,
    "Ice Spirit": 1,
    "Fire Spirit": 1,
    "Miner": 3,
    "Sparky": 6,
    "Bowler": 5,
    "Lumberjack": 4,
    "Battle Ram": 4,
    "Inferno Dragon": 4,
    "Ice Golem": 2,
    "Mega Minion": 3,
    "Dart Goblin": 3,
    "Goblin Gang": 3,
    "Electro Wizard": 4,
    "Elite Barbarians": 6,
    "Hunter": 4,
    "Executioner": 5,
    "Bandit": 3,
    "Royal Recruits": 7,
    "Night Witch": 4,
    "Bats": 2,
    "Royal Ghost": 3,
    "Ram Rider": 5,
    "Zappies": 4,
    "Rascals": 5,
    "Cannon Cart": 5,
    "Mega Knight": 7,
    "Skeleton Barrel": 3,
    "Flying Machine": 4,
    "Wall Breakers": 2,
    "Royal Hogs": 5,
    "Goblin Giant": 6,
    "Fisherman": 3,
    "Magic Archer": 4,
    "Electro Dragon": 5,
    "Firecracker": 3,
    "Mighty Miner": 4,
    "Elixir Golem": 3,
    "Battle Healer": 4,
    "Skeleton King": 4,
    "Archer Queen": 5,
    "Golden Knight": 4,
    "Monk": 5,
    "Skeleton Dragons": 4,
    "Mother Witch": 4,
    "Electro Spirit": 1,
    "Electro Giant": 7,
    "Phoenix": 4,
    "Little Prince": 3,
    "Goblin Demolisher": 4,
    "Goblin Machine": 5,
    "Suspicious Bush": 2,
    "Goblinstein": 5,
    "Rune Giant": 4,
    "Berserker": 2,
    "Boss Bandit": 6,
    "Cannon": 3,
    "Goblin Hut": 4,
    "Mortar": 4,
    "Inferno Tower": 5,
    "Bomb Tower": 4,
    "Barbarian Hut": 6,
    "Tesla": 4,
    "Elixir Collector": 6,
    "X-Bow": 6,
    "Tombstone": 3,
    "Furnace": 4,
    "Goblin Cage": 4,
    "Goblin Drill": 4,
    "Fireball": 4,
    "Arrows": 3,
    "Rage": 2,
    "Rocket": 6,
    "Goblin Barrel": 3,
    "Freeze": 4,
    "Mirror": 0,
    "Lightning": 6,
    "Zap": 2,
    "Poison": 4,
    "Graveyard": 5,
    "The Log": 2,
    "Tornado": 3,
    "Clone": 3,
    "Earthquake": 3,
    "Barbarian Barrel": 2,
    "Heal Spirit": 1,
    "Giant Snowball": 2,
    "Royal Delivery": 3,
    "Void": 3,
    "Goblin Curse": 2,
    "Spirit Empress": 6,
    "Vines": 3,
}
